---

- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install deps for openshift-ansible
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - pyOpenSSL
    - python-cryptography
    - python-lxml

- name: Set repo fact
  set_fact:
    openshift_ansible_repo: "https://github.com/openshift/openshift-ansible.git"
  when: openshift_ansible_repo is not defined

- name: Set repo version fact
  set_fact:
    openshift_ansible_version: master
  when: openshift_ansible_version is not defined


- name: Clone openshift-ansible
  git:
    repo: "{{ openshift_ansible_repo }}"
    version: "{{ openshift_ansible_version }}"
    dest: /root/openshift-ansible
    force: yes