---

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - virt-manager
    - libvirt
    - libvirt-daemon-kvm
    - nano
    - tcpdump
    - net-tools
    - libvirt-client
    - virt-install
    - genisoimage
    - nmap

- name: Start and enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Make directory to store images...
  file:
    path: "{{ images_directory }}"
    state: directory

- name: Download CentOS cloud image
  get_url:
    url: "{{ centos_genericcloud_url }}"
    dest: "{{ images_directory }}/{{ image_destination_name }}"
  register: download_image

- name: Increase root disk size
  shell: >
    qemu-img resize {{ images_directory }}/{{ image_destination_name }} +{{ increase_root_size_gigs }}G
  when: download_image.changed

- name: Generate an ssh key for root
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_vm_rsa

# Alright, we should fix up the
- name: "Include bridge network playbook if necessary"
  include: bridge-network.yml
  when: bridge_networking
